

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_


#define ULTRASONIC_TRIGGER_PORTID PORTD_ID
#define ULTRASONIC_TRIGGER_PINID  PIN7_ID


#include "std_types.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
/*
 *  Description :1- Initialize the ICU driver as required.
                 2- Setup the ICU call back function.
                 3- Setup the direction for the trigger pin as output pin through the GPIO driver.

 * */
void Ultrasonic_init(void);

/*
• Description : Send the Trigger pulse to the ultrasonic.
•
 */

void Ultrasonic_Trigger(void);

/*
• Description : 1- Send the trigger pulse by using Ultrasonic_Trigger function.
                2- Start the measurements by the ICU from this moment.

 */

uint16 Ultrasonic_readDistance(void);

/*
 • Description : 1-This is the call back function called by the ICU driver.
               : 2-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.

 */

void Ultrasonic_edgeProcessing(void);
/*
 *
 * Description:
▪ This is the callback function called by the ICU driver.
▪ It calculates the high time (pulse time) generated by
the ultrasonic sensor.

*/
#endif
